FROM nginx:1.23.1
RUN rm -f /etc/nginx/conf.d/default.conf  # 删除默认配置
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/tekton.conf /etc/nginx/conf.d/tekton.conf
COPY dist-admin /usr/share/nginx/tekton
EXPOSE 8677 443
CMD ["nginx", "-g", "daemon off;"]
